<?php
namespace ProcessWire;

class ProcessWesanoxApi extends Process implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title' => 'wesanox API Process',
            'summary' => 'A little API Connector for Processwire.',
            'version' => '0.5.0',
            'author' => 'wesanox',
            'icon' => 'cogs',
            'page'       => array(
                'name' => 'wesanox-api',
                'parent' => 'setup',
                'title' => 'Apis',
            ),
            'requires' => 'WesanoxApi',
        );
    }

    protected Page $template_options;

    public function __construct()
    {
        $this->template_options = $this->pages->get('template=options_generals');
    }

    /**
     * @return void
     * @throws WireException
     * @throws WirePermissionException
     */
    public function init() : void
    {
        $this->wire('modules')->get('JqueryUI')->use('vex');
        parent::init();
    }

    /**
     * @return string
     * @throws WirePermissionException
     */
    public function ___execute() : string
    {
        $button = $this->modules->get('InputfieldButton');
        $button->value = __('Add new');
        $button->icon = 'plus-circle';
        $button->attr('href', './add/');
        $addButton = $button->render();

        // Return view data
        return $this->renderTable() . $addButton;
    }

    /**
     * @return mixed
     * @throws WirePermissionException
     */
    public function ___executeAdd(): string
    {
        if ($this->input->post->submit) {
            $this->saveApi(null, $this->input->post);

            $this->session->redirect($this->page->url);;
        } else {
            $data = [];
        }

        $form = $this->buildForm($data);
        return $form->render();
    }

    /**
     * @return string
     */
    public function ___executeEdit(): string
    {
        $id = $this->input->get('id');
        $api = $this->template_options->repeater_api->get("id=$id");

        if (!$api instanceof Page || !$api->id) {
            $this->error(__("API mit ID $id nicht gefunden"));
        }

        if ($this->input->post->submit) {
            $data = $this->saveApi($id, $this->input->post);
        } else {
            $data = [
                'api_name' => $api->api_name,
                'api_url' => $api->api_url,
                'api_select_method' => $api->api_select_method,
                'api_username' => $api->api_username,
                'api_password' => $api->api_password,
                'api_key' => $api->api_key,
                'api_secret' => $api->api_secret,
            ];
        }

        if ($this->input->get('try')) {
            $response = $this->tryApi($id);
            $content = json_decode($response);

            if ($content->status === 'error') {
                $this->error(__($content->data));
            } elseif ($content->status === 'success') {
                $this->message(__($content->data));
            } else {
                $this->error(__($response));
            }
        }

        $form = $this->buildForm($data, $id);
        $form->action = $this->page->url . 'edit?id=' . $id;

        return $form->render();
    }

    /**
     * @return void
     * @throws WireException
     */
    public function ___executeDelete() : void
    {
        $id = $this->input->get('id');

        $this->deleteApi($id);

        $this->message(__('Api deleted'));

        $this->session->redirect($this->page->url);
    }

    /**
     * @return _Module|Module|string|null
     * @throws WireException
     * @throws WirePermissionException
     */
    private function buildForm(array $data = [], string $id = null): InputfieldForm
    {
        $form = $this->modules->get('InputfieldForm');
        $wrapper = $this->modules->get('InputfieldWrapper');

        $defaults = [
            'api_name' => '',
            'api_url' => '',
            'api_select_method' => '',
            'api_username' => '',
            'api_password' => '',
            'api_key' => '',
            'api_secret' => '',
        ];

        $data = array_merge($defaults, $data);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('Api Name');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 50;
        $f->attr('name', 'api_name');
        $f->attr('value', $data['api_name']);
        $f->required = true;
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('API URL');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 25;
        $f->attr('name', 'api_url');
        $f->attr('value', $data['api_url']);
        $f->required = true;
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldSelect');
        $f->label = __('API Method');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 25;
        $f->attr('name', 'api_select_method');
        $f->attr('value', $data['api_select_method']);
        $f->addOptions([
                1 => 'No Auth',
                2 => 'API Key',
                3 => 'Bearer Token',
                4 => 'Basic Auth'
            ]);
        $f->required = true;
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('API Username');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 50;
        $f->attr('name', 'api_username');
        $f->attr('value', $data['api_username']);
        $f->showIf = 'api_select_method=4';
        $f->requiredIf = 'api_select_method=4';
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('API Password / Token');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = ($data['api_select_method'] === 3) ? 100 : 50;
        $f->attr('name', 'api_password');
        $f->attr('value', $data['api_password']);
        $f->showIf = 'api_select_method=3|4';
        $f->requiredIf = 'api_select_method=3|4';
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('API Key');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 50;
        $f->attr('name', 'api_key');
        $f->attr('value', $data['api_key']);
        $f->showIf = 'api_select_method=2';
        $f->requiredIf = 'api_select_method=2';
        $wrapper->add($f);

        $f = $this->modules->get('InputfieldText');
        $f->label = __('API Secret');
        $f->description = __('Any combination of letters (a-z), numbers (0-9).');
        $f->columnWidth = 50;
        $f->attr('name', 'api_secret');
        $f->attr('value', $data['api_secret']);
        $f->showIf = 'api_select_method=2';
        $wrapper->add($f);

        $submit = $this->modules->get('InputfieldSubmit');
        $submit->attr('name', 'submit');
        $submit->attr('value', __('Save'));
        $wrapper->add($submit);

        // Test-Button nur bei Edit
        if ($id !== null) {
            $buttonTry = $this->modules->get('InputfieldButton');
            $buttonTry->value = __('Test Connection');
            $buttonTry->attr('href', './edit?id=' . $id . '&try=1');
            $wrapper->add($buttonTry);
        }

        $form->add($wrapper);
        return $form;
    }

    /**
     * Add new API - Item or edit existing API - Item
     *
     * @param string|null $id
     * @param $api_name
     * @return Page|null
     * @throws WireException
     */
    private function saveApi(?string $id, $api_data): array|null
    {
        $this->template_options->of(false);

        $api_name = $this->sanitizer->text($api_data->api_name);
        $api_url = $this->sanitizer->url($api_data->api_url);
        $api_select_method = $this->sanitizer->int($api_data->api_select_method);
        $api_username = $this->sanitizer->text($api_data->api_username);
        $api_password = $this->sanitizer->text($api_data->api_password);
        $api_key = $this->sanitizer->text($api_data->api_key);
        $api_secret = $this->sanitizer->text($api_data->api_secret);

        if (!$api_name || !$api_url || !$api_select_method) {
            $this->error(__('Please fill in the required fields'));
            return null;
        }

        if ($id) {
            $api = $this->template_options->repeater_api->get("id=$id");

            if (!$api instanceof Page || !$api->id) {
                $this->error(__("API with ID $id not found"));
            }

            $api->of(false);
        } else {
            $api = $this->template_options->repeater_api->getNew();
        }

        $api->api_name = $api_name;
        $api->api_url = $api_url;
        $api->api_select_method = $api_select_method;
        $api->api_username = $api_username;
        $api->api_password = $api_password;
        $api->api_key = $api_key;
        $api->api_secret = $api_secret;
        $api->save();

        $this->template_options->save();

        $this->message(__('Api added'));

        return compact('api_name', 'api_url', 'api_select_method', 'api_username', 'api_password', 'api_key', 'api_secret');
    }

    /**
     * @param $id
     * @return mixed
     * @throws WireException
     * @throws WirePermissionException
     */
    private function tryApi($id)
    {
        return $this->modules->get('WesanoxApi')->requestByApiId((int)$id, 'hello');
    }

    /**
     * @return void
     */
    private function deleteApi($id): void
    {
        $api = $this->template_options->repeater_api->get("id=$id");

        $this->template_options->of(false);

        $api->delete();

        $this->template_options->save();
    }

    /**
     * @return mixed
     * @throws WirePermissionException
     */
    private function renderTable() : mixed
    {
        $table = $this->modules->get('MarkupAdminDataTable');

        $table->setSortable(false);
        $table->setEncodeEntities(false);
        $table->headerRow([__('Api Name'), __('Actions')]);

        foreach ( $this->template_options->repeater_api AS $api) {
            $buttonDelete = $this->modules->get('InputfieldButton');
            $buttonDelete->value = 'delete';
            $buttonDelete->icon = 'trash';
            $buttonDelete->setSmall()->setSecondary();
            $buttonDelete->attr('href', './delete/?id=' . $api->id);
            $buttonDelete->addClass('InputfieldButtonLink');

            $buttonTry = $this->modules->get('InputfieldButton');
            $buttonTry->value = __('Test Connection');
            $buttonTry->icon = 'cogs';
            $buttonTry->setSmall()->setSecondary();
            $buttonTry->attr('href', './edit?id=' . $api->id . '&try=1');
            $buttonTry->addClass('InputfieldButtonLink');

            $table->row([
                '<a href="./edit?id=' . $api->id . '">' . $api->api_name . "</a>",
                $buttonDelete->render() . $buttonTry->render(),
            ]);
        }

        return $table->render();
    }
}